include:
 - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/34039cd573a2df832d465bc9e4c5f543571f5241/templates/ci-fairy.yml'

stages:
 - build
 - deploy

default:
  # Protect CI infra from rogue jobs
  timeout: 15 minutes
  # Allow jobs to be caneled on new commits
  interruptible: true
  # Retry on infra hickups automatically
  retry:
    max: 1
    when:
      - 'api_failure'
      - 'runner_system_failure'
      - 'scheduler_failure'
      - 'stuck_or_timeout_failure'

variables:
  # For ci-fairy
  FDO_UPSTREAM_REPO: guidog/phosh-wallpapers
  DEBIAN_IMAGE: $CI_REGISTRY/guidog/phosh-osk-stub/debian:v0.0.2024-05-03

.prep: &prep
  before_script:
    - apt-get -y update
    - apt-get -y build-dep .

.step: &build_step
  script:
    - dpkg-buildpackage -uc -us -rfakeroot -A
    - mkdir -p out/
    - 'cp ../phosh-wallpapers_$(dpkg-parsechangelog -SVersion)_all.deb out/'

# Sanity checks of MR settings and commit logs
sanity:
  extends:
    - .fdo.ci-fairy
  stage: build
  script: |
    if [ -n "$CI_OPEN_MERGE_REQUESTS" ]; then
      ci-fairy check-commits --junit-xml=commit-message-junit-report.xml cifairy/main..HEAD ;
    else
      echo "Not a merge request" ;
    fi
  artifacts:
    reports:
      junit: commit-message-junit-report.xml
  only:
    variables:
      - $CI_OPEN_MERGE_REQUESTS && $PKG_ONLY != "1"

build:native-debian-bookworm:
  stage: build
  image: ${DEBIAN_IMAGE}
  <<: *prep
  <<: *build_step
  artifacts:
    paths:
      - out/
